
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/backend/
    ports:
      - 8000:8000
    env_file:
      - ./local.env
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=backend_admin
      - POSTGRES_PASSWORD=backend_admin
      - POSTGRES_DB=backend_admin_dev

volumes:
  postgres_data: